package com.niyamstack.propel.catalog;

import java.util.List;

public final class Features {
    private Features() {}

    public static final List<Feature> ALL = List.of(
            f(1, "Platform & Access", "Multi-branch / Multi-center", "Manage multiple centers/locations with shared or separated operations.", "Growth", "Should Have", "Growth", false),
            f(2, "Institute Setup", "Organization Profile", "Institute legal details, centers, contacts, and operating settings.", "Foundation", "Must Have", "Starter", false),
            f(3, "Institute Setup", "Academic Year & Terms", "Configure academic years, terms/semesters, and active periods.", "Foundation", "Must Have", "Starter", false),
            f(4, "Institute Setup", "Course Catalog", "Create courses/programs with duration, fees, eligibility, and outcomes.", "Foundation", "Must Have", "Starter", false),
            f(5, "Institute Setup", "Batch Management", "Create batches, capacity, faculty mapping, and batch lifecycle.", "Foundation", "Must Have", "Starter", false),
            f(6, "Institute Setup", "Classroom / Resource Master", "Manage classrooms, labs, and resource allocation for sessions.", "Growth", "Should Have", "Growth", false),
            f(7, "Institute Setup", "Custom Fields & Form Builder", "Add institute-specific fields/forms without code changes.", "Growth", "Should Have", "Growth", false),
            f(8, "Institute Setup", "Workflow / Approval Builder", "Configurable approvals for admissions, discounts, fee waivers, offers.", "Scale", "Should Have", "Enterprise", false),
            f(9, "Institute Setup", "Document Template Engine", "Configurable templates for receipts, certificates, offer letters, ID cards.", "Growth", "Must Have", "Growth", false),
            f(10, "CRM & Admissions", "Inquiry / Lead Capture", "Capture walk-in, web, referral, and campaign leads with source tracking.", "Foundation", "Must Have", "Starter", false),
            f(11, "CRM & Admissions", "Counseling Pipeline", "Stage-wise counseling follow-ups, notes, and next actions.", "Foundation", "Must Have", "Starter", false),
            f(12, "CRM & Admissions", "Online Admission Forms", "Public/web admission applications with document upload.", "Growth", "Must Have", "Growth", false),
            f(13, "CRM & Admissions", "Eligibility Rules Engine", "Auto-check course/drive eligibility by marks, attendance, skills, batch.", "Growth", "Should Have", "Growth", false),
            f(14, "CRM & Admissions", "Admission Conversion", "Convert inquiry to enrolled student with course/batch allocation.", "Foundation", "Must Have", "Starter", false),
            f(15, "CRM & Admissions", "Referral & Affiliate Tracking", "Track student/agent referrals and incentive attribution.", "Scale", "Should Have", "Enterprise", false),
            f(16, "CRM & Admissions", "Campaign & Funnel Analytics", "Measure lead source ROI, conversion rates, and counselor performance.", "Growth", "Should Have", "Growth", false),
            f(17, "CRM & Admissions", "Scholarship / Discount Management", "Define scholarships/discounts with approval and accounting impact.", "Growth", "Should Have", "Growth", false),
            f(18, "Student Information System", "Student Master Profile", "Single student record with unique ID across all modules.", "Foundation", "Must Have", "Starter", false),
            f(19, "Student Information System", "Student Documents Vault", "Store Aadhaar, marksheets, photos, agreements, and certificates.", "Foundation", "Must Have", "Starter", false),
            f(20, "Student Information System", "Guardian / Parent Linking", "Link parents/guardians with controlled visibility and notifications.", "Foundation", "Must Have", "Starter", false),
            f(21, "Student Information System", "Student Lifecycle Status", "Track inquiry, enrolled, active, deferred, alumni, dropped statuses.", "Foundation", "Must Have", "Starter", false),
            f(22, "Student Information System", "ID Card Generation", "Generate printable/digital student ID cards.", "Growth", "Should Have", "Growth", false),
            f(23, "Student Information System", "Bulk Import / Migration", "Excel/CSV import and migration tools from legacy systems.", "Foundation", "Must Have", "Starter", false),
            f(24, "Student Information System", "Data Deduplication", "Detect and merge duplicate student/lead records.", "Growth", "Should Have", "Growth", false),
            f(25, "Academics & Delivery", "Timetable Management", "Create and publish class schedules by batch/faculty/room.", "Foundation", "Must Have", "Starter", false),
            f(26, "Academics & Delivery", "Attendance Management", "Session/day attendance marking, shortages, and summaries.", "Foundation", "Must Have", "Starter", false),
            f(27, "Academics & Delivery", "Biometric / Device Attendance", "Integrate biometric/RFID/device attendance punches.", "Scale", "Should Have", "Enterprise", false),
            f(28, "Academics & Delivery", "Learning Content Library", "Notes, PDFs, videos, and batch-wise content distribution.", "Foundation", "Must Have", "Starter", false),
            f(29, "Academics & Delivery", "Live Class Integration", "Integrate Zoom/Meet/Teams or native live sessions.", "Growth", "Should Have", "Growth", false),
            f(30, "Academics & Delivery", "Recorded Lectures", "Store and stream recorded sessions with access control.", "Growth", "Should Have", "Growth", false),
            f(31, "Academics & Delivery", "Assignments & Submissions", "Assign work, collect submissions, grade, and feedback.", "Foundation", "Must Have", "Starter", false),
            f(32, "Academics & Delivery", "Assessments & Exam Engine", "MCQ/descriptive tests, scheduling, scoring, and result publish.", "Foundation", "Must Have", "Starter", false),
            f(33, "Academics & Delivery", "Online Proctoring Basics", "Browser lockdown/proctoring flags for high-stakes tests.", "Scale", "Could Have", "Enterprise", false),
            f(34, "Academics & Delivery", "Question Bank", "Reusable question bank by subject, topic, and difficulty.", "Growth", "Should Have", "Growth", false),
            f(35, "Academics & Delivery", "Doubt Forum / Tickets", "Structured doubt raising and faculty response tracking.", "Growth", "Should Have", "Growth", false),
            f(36, "Academics & Delivery", "Faculty Workload Planning", "Track faculty allocation, hours, and load balancing.", "Growth", "Should Have", "Growth", false),
            f(37, "Academics & Delivery", "Progress Tracking Dashboard", "Student/faculty view of syllabus completion and performance.", "Foundation", "Must Have", "Starter", false),
            f(38, "Academics & Delivery", "Certificate of Completion", "Auto-generate course/module completion certificates.", "Growth", "Should Have", "Growth", false),
            f(39, "Fees & Finance", "Fee Structure Builder", "Course/batch fee plans, components, taxes, and installments.", "Foundation", "Must Have", "Starter", false),
            f(40, "Fees & Finance", "Fee Collection & Receipts", "Collect fees, generate receipts, and maintain ledgers.", "Foundation", "Must Have", "Starter", false),
            f(41, "Fees & Finance", "Dues & Reminder Automation", "Automatic dues tracking and multi-channel reminders.", "Foundation", "Must Have", "Starter", false),
            f(42, "Fees & Finance", "Payment Gateway Integration", "Online payments via Razorpay/Cashfree/etc.", "Growth", "Must Have", "Growth", false),
            f(43, "Fees & Finance", "GST Invoicing", "GST-compliant invoices, credit notes, and tax reports.", "Growth", "Must Have", "Growth", false),
            f(44, "Fees & Finance", "Refunds & Adjustments", "Controlled refunds, adjustments, and approval trails.", "Growth", "Should Have", "Growth", false),
            f(45, "Fees & Finance", "Cheque / Offline Payment Reconciliation", "Track offline modes and bank reconciliation.", "Growth", "Should Have", "Growth", false),
            f(46, "Fees & Finance", "Accounting Export", "Export fee data to Tally/Zoho Books/QuickBooks.", "Scale", "Should Have", "Enterprise", false),
            f(47, "Fees & Finance", "Financial Dashboards", "Collection %, outstanding, counselor-wise and course-wise revenue.", "Growth", "Must Have", "Growth", false),
            f(48, "Communication", "Omnichannel Notifications", "Email, SMS, WhatsApp, and in-app notifications.", "Foundation", "Must Have", "Starter", false),
            f(49, "Communication", "WhatsApp Business Integration", "Templates for fees, attendance, tests, and drive alerts.", "Growth", "Must Have", "Growth", false),
            f(50, "Communication", "Announcement Center", "Institute/batch announcements with read acknowledgements.", "Foundation", "Must Have", "Starter", false),
            f(51, "Communication", "Parent Portal / App View", "Parents view attendance, fees, results, and notices.", "Growth", "Must Have", "Growth", false),
            f(52, "Communication", "Communication Templates", "Reusable approved templates by event type.", "Foundation", "Must Have", "Starter", false),
            f(53, "Communication", "Conversation Inbox", "Central inbox for student/parent queries (light CRM).", "Scale", "Could Have", "Enterprise", false),
            f(54, "Placement Readiness", "Skills Inventory", "Student skills, projects, certifications, and proficiency.", "Foundation", "Must Have", "Starter", false),
            f(55, "Placement Readiness", "Resume Manager", "Resume versions, templates, and completeness scoring.", "Foundation", "Must Have", "Starter", false),
            f(56, "Placement Readiness", "AI Resume Suggestions", "Improve resume content/structure using AI assistance.", "Scale", "Should Have", "Enterprise", false),
            f(57, "Placement Readiness", "Mock Interviews", "Schedule mocks, scorecards, and feedback history.", "Growth", "Should Have", "Growth", false),
            f(58, "Placement Readiness", "AI Mock Interview Coach", "AI-led practice interviews with feedback.", "Scale", "Could Have", "Enterprise", false),
            f(59, "Placement Readiness", "Coding / Aptitude Practice", "Practice sets, contests, and readiness tracking.", "Growth", "Should Have", "Growth", false),
            f(60, "Placement Readiness", "Placement Readiness Score", "Composite score from academics, skills, attendance, mocks.", "Growth", "Should Have", "Growth", true),
            f(61, "Placement Readiness", "Career Path Mapping", "Map students to target roles and recommended upskilling.", "Scale", "Should Have", "Enterprise", false),
            f(62, "Placement Readiness", "At-Risk Student Engine", "Detect dropout/low-placement-risk students early.", "Growth", "Should Have", "Growth", false),
            f(63, "Placement Operations", "Company / Recruiter Master", "Company profiles, contacts, hiring preferences, and history.", "Foundation", "Must Have", "Starter", false),
            f(64, "Placement Operations", "Job / Drive Management", "Create drives with JD, package, locations, and deadlines.", "Foundation", "Must Have", "Starter", false),
            f(65, "Placement Operations", "Eligibility Auto-filter", "Auto-shortlist eligible students by configurable rules.", "Growth", "Should Have", "Growth", false),
            f(66, "Placement Operations", "Application Tracking System", "Track applied / shortlisted / interviewed / offered / joined.", "Foundation", "Must Have", "Starter", false),
            f(67, "Placement Operations", "Interview Round Manager", "Multi-round tracking with panel feedback and outcomes.", "Foundation", "Must Have", "Starter", false),
            f(68, "Placement Operations", "Offer Management", "Offer letters, acceptance, negotiation notes, joining dates.", "Growth", "Should Have", "Growth", false),
            f(69, "Placement Operations", "Recruiter Portal", "External recruiter login to view pools and update statuses.", "Growth", "Should Have", "Growth", false),
            f(70, "Placement Operations", "Placement Calendar", "Shared calendar of drives, deadlines, and interviews.", "Foundation", "Should Have", "Starter", false),
            f(71, "Placement Operations", "Outcome & Package Analytics", "Placement %, average package, company-wise and course-wise stats.", "Growth", "Should Have", "Growth", false),
            f(72, "Placement Operations", "Internship Management", "Track internships separately from full-time placements.", "Growth", "Should Have", "Growth", false),
            f(73, "Alumni & Industry", "Alumni Directory", "Alumni profiles, companies, and engagement status.", "Growth", "Should Have", "Growth", false),
            f(74, "Alumni & Industry", "Alumni Referral Jobs", "Capture and route alumni-referred opportunities.", "Scale", "Should Have", "Enterprise", false),
            f(75, "Alumni & Industry", "Industry CRM", "MoUs, campus visits, relationship owners, and hiring cycles.", "Scale", "Should Have", "Enterprise", false),
            f(76, "Alumni & Industry", "Guest Lecture / Event Management", "Plan industry sessions and track attendance/feedback.", "Scale", "Could Have", "Enterprise", false),
            f(77, "Analytics & Admin", "Role-based Dashboards", "Tailored home dashboards for each major role.", "Foundation", "Must Have", "Starter", false),
            f(78, "Analytics & Admin", "KPI Scorecards", "Conversion, attendance, collections, readiness, placement KPIs.", "Growth", "Should Have", "Growth", false),
            f(79, "Analytics & Admin", "Report Builder", "Configurable operational and management reports.", "Growth", "Should Have", "Growth", false),
            f(80, "Analytics & Admin", "Scheduled Report Delivery", "Auto-email weekly/monthly reports to management.", "Scale", "Should Have", "Enterprise", false),
            f(81, "Analytics & Admin", "Data Export Center", "Secure exports with access control and masking options.", "Foundation", "Must Have", "Starter", false),
            f(82, "Analytics & Admin", "Support Tickets (Student/Staff)", "Internal helpdesk for academic/admin issues.", "Growth", "Should Have", "Growth", false),
            f(83, "Mobile & Ecosystem", "Student Mobile App", "Attendance, content, fees, notifications, and applications on mobile.", "Growth", "Must Have", "Growth", false),
            f(84, "Mobile & Ecosystem", "Faculty Mobile App", "Mark attendance, publish notices, grade, and view batches on mobile.", "Growth", "Must Have", "Growth", false),
            f(85, "Mobile & Ecosystem", "Marketplace Integrations", "Prebuilt connectors for Zoom, payment gateways, WhatsApp, etc.", "Scale", "Should Have", "Enterprise", false),
            f(86, "Mobile & Ecosystem", "Offline Mode Basics", "Limited offline actions with later sync for weak connectivity.", "Scale", "Could Have", "Enterprise", false),
            f(87, "Analytics", "Learning Outcome Analytics", "Measure learning outcomes and employability impact by course/batch.", "Scale", "Should Have", "Enterprise", false),
            f(88, "Academics & Delivery", "LMS Standards Support (SCORM/xAPI/LTI)", "Support content portability and external LMS interoperability.", "Scale", "Should Have", "Enterprise", false),
            f(89, "Placement Readiness", "AI Academic Assistant", "Personalized study plans, recommendations, and AI tutor chatbot.", "Scale", "Should Have", "Enterprise", true),
            f(90, "Analytics", "Faculty Performance Analytics", "Track faculty outcomes, content contribution, attendance effectiveness, feedback.", "Scale", "Should Have", "Enterprise", false),
            f(91, "Compliance & Commercial", "Accreditation Management", "Evidence and workflows for NAAC/NBA/ISO/skill-agency accreditation needs.", "Scale", "Should Have", "Enterprise", false),
            f(92, "Student Information System", "Student Success CRM", "Automated interventions for low attendance, poor performance, dropout risk.", "Growth", "Should Have", "Growth", true),
            f(93, "Placement Readiness", "AI Career Coach", "Career planning, skill roadmap, and intelligent job matching.", "Scale", "Should Have", "Enterprise", true),
            f(94, "Placement Operations", "Placement Salary Benchmarking", "Salary intelligence by role, city, company, and course.", "Scale", "Should Have", "Enterprise", true),
            f(95, "Alumni & Industry", "Employer Engagement Portal", "Broader recruiter relationship and engagement workspace beyond single drives.", "Scale", "Should Have", "Enterprise", true)
    );

    private static Feature f(int n, String cat, String name, String desc, String tier, String pri, String pkg, boolean diff) {
        return new Feature(n, cat, name, desc, tier, pri, pkg, diff);
    }
}
